export const REQUEST_API_DATA = 'REQUEST_API_DATA';
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA';
export const REQUEST_API_DATA_FAILED = 'REQUEST_API_DATA_FAILED';
export const SEARCH = 'SEARCH';
export const SAVE_SEARCH = 'SAVE_SEARCH';
export const REQUEST_PAGE_NUMBER = 'REQUEST_PAGE_NUMBER';
export const RECEIVE_PAGE_NUMBER = 'RECEIVE_PAGE_NUMBER';
