export const REQUEST_API_DATA = 'REQUEST_API_DATA';
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA';

export const SEARCH = 'SEARCH';
export const SAVE_SEARCH = 'SAVE_SEARCH';

export const REQUEST_PAGE_NUMBER = 'REQUEST_PAGE_NUMBER';
export const RECEIVE_PAGE_NUMBER = 'RECEIVE_PAGE_NUMBER';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
